### ISSUE TITLE
How should we name this repo?

### ISSUE THREAD

**Issue by hiagofranco** [hiagofranco/Brict-ToradexInformationTool#8]
The name that I created is very bad... It doesn't tell the viewer what it's about. How should we name it? @leograba

**Comment by leograba** [comment]
Names sound good ❤️

> About dropping the .sh, how does it work? Linux can call this script without .sh? I don't have much experience with shell scripts.

This is actually even more generic. Linux doesn't care about file extensions at all. They are just abstractions people use. There could be a text file named `mytextfile` or `mytextfile.asdf` instead of `mytextfile.txt` and Linux wouldn't care. Some applications might care - for example when you are about to open a file and the app only shows files with a specific extension, but it isn't a Linux thing.

With executables, it is about the executable flag. No matter what is the executable name and no matter if it's a script or a compiled app, once you `chmod` passing the `+x` option (https://askubuntu.com/questions/29589/chmod-ux-versus-chmod-x), it becomes executable.

Then, how does Linux know the "otherwise plain text file" is an executable? That is because of the https://en.wikipedia.org/wiki/Shebang_(Unix). On the current script, it tells the system to use whatever shell is symlinked to `/bin/sh`, whether it is Bash or something else. it is also often used in Python scripts so they can be invoked directly, without explicitly invoking Python, e.g. `./mypythonapp.py` or `./mypythonapp` instead of `python mypythonapp.py` or `python mypythonapp`.

p.s.1. I like it that the script uses the `#!/bin/sh` shebang and does not use Bashisms. That makes it more resilient to systems that use another shell interpreter by default (Dash, Busybox, Zsh, etc.). For example, our Reference Minimal images don't include Bash if I'm not mistaken:

```
leonardo@leonardoveiga-pc:ref-images$ ls
Apalis-iMX6_Console-Image-Tezi_3.0b4.254                    Apalis-T30_LXDE-Image-Tezi_2.7                                      Colibri-iMX6ULL_Reference-Minimal-Image-Tezi_5.6.0+build.18
Apalis-iMX6_LXDE-Image-Tezi_2.8b8                           Apalis-TK1_L4T-Image-Tezi_21.7-2.8b6                                Colibri-iMX6ULL_Reference-Minimal-Image-upstream-Tezi_5.6.0+build.18
Apalis-iMX8_Reference-Multimedia-Image-Tezi_5.6.0+build.18  Apalis-TK1_Reference-Multimedia-Image-upstream-Tezi_5.6.0+build.18
leonardo@leonardoveiga-pc:ref-images$ ls | wc -l
8
leonardo@leonardoveiga-pc:ref-images$ find . -name "bash" | grep "bin/bash"
./Apalis-T30_LXDE-Image-Tezi_2.7/rootfs/bin/bash
./Apalis-TK1_L4T-Image-Tezi_21.7-2.8b6/rootfs/bin/bash
./Apalis-iMX6_Console-Image-Tezi_3.0b4.254/rootfs/bin/bash
./Apalis-iMX6_LXDE-Image-Tezi_2.8b8/rootfs/bin/bash
./Apalis-iMX8_Reference-Multimedia-Image-Tezi_5.6.0+build.18/rootfs/bin/bash
./Apalis-TK1_Reference-Multimedia-Image-upstream-Tezi_5.6.0+build.18/rootfs/bin/bash
leonardo@leonardoveiga-pc:ref-images$ find . -name "bash" | grep "bin/bash" | wc -l
6
```

p.s.2. On a related note, in all comments from my last PR, I have consciously (to the extent of my knowledge) used commands and comparisons that are more generic and should work on shells other than Bash. Of course, ShellCheck also helped a lot with it. And arguably, `` `...` `` is more backward compatible than `$(...)` but that is so unlikely to happen with people using our scripts - nobody running it on a 20-year-old (this is a wild guess, don't quote me on the exact number!) distro hopefully - that the benefits outweigh the marginally increased portability.

p.s.3. On commit https://github.com/hiagofranco/tdx-version/commit/67f24c9477a1a458e1af6199fbbbe59336e647f0 I have implicitly and unintentionally set the executable flag. You can notice on GitHub with the `100644 → 100755`. I just realize that now, because we came into the topic, so I searched the exact commit with https://stackoverflow.com/questions/16529597/find-the-commit-that-changed-file-permissions. It isn't a big issue, as the script is intended to be an executable, but it should have been on an explicit commit I think. I'll pay more attention to it in the future.

**Comment by hiagofranco** [comment]
Amazing Explanation @leograba, thanks a lot! I learned a lot with just a comment hahahah

Ok, I'll update the name of the repo and create a PR for us to change the name of this script.
Cheers!

**Comment by hiagofranco** [comment]
Changed name of the repo to "Brict-ToradexInformationTool", "Brict - Commandline System Information Tool for Toradex" was too long.
